version: "3.9"
services:
  app:
    build:
      context: ./python
      dockerfile: Dockerfile
    image: build2023/app:latest 
    ports:
      - "9000:9000"
    volumes:
      - ./python:/app/python
      - ./python/images:/app/python/images
      - ./db:/app/db
    environment: 
      - FRONT_URL=http://localhost:3000


  web:
    build:
      context: ./typescript/simple-mercari-web
      dockerfile: Dockerfile
    image: build2023/web:latest
    ports:
      - "3000:3000"
    volumes:
      - ./typescript/simple-mercari-web:/home/typescript/simple-mercari-web
      - ./typescript/simple-mercari-web/node_modules:/home/typescript/simple-mercari-web/node_modules
      - ./typescript/simple-mercari-web/src:/home/typescript/simple-mercari-web/src
      - ./typescript/simple-mercari-web/public:/home/typescript/simple-mercari-web/public
    environment: 
      - REACT_APP_API_URL=http://127.0.0.1:9000

